//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.AdditionalProducts = new HashSet<AdditionalProduct>();
            this.Sales = new HashSet<Sale>();
            this.WareHouses = new HashSet<WareHouse>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public int CategoryProductID { get; set; }
        public int Price { get; set; }
        public string Feature { get; set; }
        public string Description { get; set; }
        public double Weight { get; set; }
        public double Width { get; set; }
        public double Lenght { get; set; }
        public int ProducID { get; set; }
        public string PhotoMain { get; set; }
        public string PhotoAdd { get; set; }
        public int SeasonID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalProduct> AdditionalProducts { get; set; }
        public virtual CategoryProduct CategoryProduct { get; set; }
        public virtual Produc Produc { get; set; }
        public virtual Season Season { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WareHouse> WareHouses { get; set; }
    }
}
