//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Entities
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Deliveries = new HashSet<Delivery>();
            this.TimeSheets = new HashSet<TimeSheet>();
        }


        public string GetPhoto
        {
            get
            {
                return $@"{Directory.GetCurrentDirectory()}\Images\{MainPhoto}";
            }
        }

        public int GetSale
        {
            get
            {
                if (Sale == 5)
                {
                    return 5;
                }
                else if (Sale == 10)
                {
                    return 10;
                }
                else if (Sale == 15)
                {
                    return 15;
                }
                else if (Sale == 20)
                {
                    return 20;
                }
                else if (Sale == 25)
                {
                    return 25;
                }
                else
                {
                    return 0;
                }
            }
        }

        public string GetColor
        {
            get
            {
                if (Sale > 0)
                    return "#90EE90";
                else
                    return "#ffffff";
            }
        }

        public double GetPrice
        {
            get
            {
                if (GetSale > 0)
                {
                    return Price * (1 - (GetSale * 0.01));
                }
                else
                {
                    return 0;
                }
            }
        }


        public string GetStrngSale
        {
            get
            {
                if (GetSale >= 5)
                {
                    return "От 0% до 5%";
                }
                if (GetSale < 5)
                {
                    return "От 5% до 15%";
                }
                if (GetSale < 15)
                {
                    return "От 15% до 30%";
                }
                if (GetSale < 30)
                {
                    return "От 30% до 70%";
                }
                if (GetSale < 70)
                {
                    return "От 70% до 100%";
                }
                else
                {
                    return "0%";
                }
            }

        }

        public int ServiceID { get; set; }
        public string Name { get; set; }
        public string MainPhoto { get; set; }
        public double Duration { get; set; }
        public double Price { get; set; }
        public Nullable<int> Sale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery> Deliveries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeSheet> TimeSheets { get; set; }
    }
}
