//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public int TimeSheetID { get; set; }
        public int EmployeeID { get; set; }
        public int ServiceID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Service Service { get; set; }
    }
}
